---

- name: New Relic Config directory
  file:
    state: directory
    path: /etc/newrelic
    owner: root
    group: root
    mode: "0755"

- name: Configure New Relic APM
  template:
    src: etc/newrelic/newrelic.ini.j2
    dest: "{{newrelic_apm_config_file}}"
    owner: root
    group: root
    mode: "0644"

# vi:ts=2:sw=2:et:ft=yaml
