---

- name: Configure New Relic APM
  template:
    src: etc/newrelic/newrelic.ini.j2
    dest: "{{newrelic_apm_config_file}}"
    owner: "{{newrelic_user}}"
    group: "{{newrelic_group}}"
    mode: "0640"

# vi:ts=2:sw=2:et:ft=yaml
