---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  tags: newrelic_install

- include: config.yml
  tags: newrelic_config

- include: apm.yml
  when: newrelic_apm_enabled

- name: Enable newrelic sysmond
  service:
    name=newrelic-sysmond
    enabled=yes
  when: newrelic_sysmond_service_enabled

# vi:ts=2:sw=2:et:ft=yaml
